spring:
  application:
    name: fdc-saga
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/fdc-cqrs-eventstore
      username: root
      password: root@1234
      max-active: 5 
      validation-query: select 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect   
    hibernate:
       ddl-auto: update
server:
  port: 9090
axon:
  amqp:
    exchange: FDC-SAGA-EXCHANGE
  eventhandling:
    processors:
      CreateQuotation:
        source: springManagedReadSAGAQueue
      HotelBookOrCancel:
        source: springManagedReadSAGAQueue
      FlightBookOrCancel:
        source: springManagedReadSAGAQueue
      CABBookOrCancel:
        source: springManagedReadSAGAQueue
  distributed:
    jgroups:
      enabled: true
      cluster-name: FDC-SAGA-CLUSTER
      gossip:
        auto-start: true
        