spring:
  application:
    name: fdc-quotation-write
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/fdc-cqrs-eventstore
      username: root
      password: root@1234
      max-active: 5 
      validation-query: select 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect   
    hibernate:
       ddl-auto: update
server:
  port: 9090
axon:
  amqp:
    exchange: FDC-QUOTATION-EXCHANGE