spring:
  application:
    name: ZIPKIN-CORE-SERVICE
  rabbitmq:
    host: localhost
    port: 5672
  sleuth:
    sampler:
      percentage: 1
    log:
      slf4j:
        enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
