spring:
  application:
    name: fdc-hotel
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/fdc-cqrs-eventstore
      username: root
      password: root@1234
      max-active: 5 
      validation-query: select 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect   
    hibernate:
       ddl-auto: update
server:
  port: 9091
axon:
  amqp:
    exchange: FDC-SAGA-EXCHANGE
  eventhandling:
    processors:
      HotelBookOrCancel:
        source: springManagedReadSAGAQueue
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   
---
spring:
  profiles: cloud
  application:
    name: fdc-hotel
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect   
    hibernate:
       ddl-auto: update
axon:
  amqp:
    exchange: FDC-SAGA-EXCHANGE
  eventhandling:
    processors:
      HotelBookOrCancel:
        source: springManagedReadSAGAQueue
management:
  security:
     enabled: false    
security:
  basic:
    enabled: false
